dd_shop_homepage:
    path:     /
    defaults: { _controller: DDShopBundle:Default:index }


DDShopBundle_category:
    resource: "@DDShopBundle/Resources/config/routing/category.yml"
    prefix:   /category

DDShopBundle_role:
    resource: "@DDShopBundle/Resources/config/routing/role.yml"
    prefix:   /role

DDShopBundle_product:
    resource: "@DDShopBundle/Resources/config/routing/product.yml"
    prefix:   /product

DDShopBundle_user:
    resource: "@DDShopBundle/Resources/config/routing/user.yml"
    prefix:   /user

account_register:
    path:     /register
    defaults: { _controller: DDShopBundle:Account:create }

account_create:
    path:     /register/create
    defaults: { _controller: DDShopBundle:Account:create }
login:
    path:     /login
    defaults: { _controller: DDShopBundle:Login:login }

login_check:
    path: /login_check
user_logout:
       pattern:   /logout
index:
    path:     /index
    defaults: { _controller: DDShopBundle:Index:index }

